services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      
    cap_add:
      - SYS_TIME
      - SYS_ADMIN
    security_opt:
    - seccomp:unconfined

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:      
                - gpu

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all        
      - TZ= Asia/Tokyo
      - MESA_LOADER_DRIVER_OVERRIDE=i965
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - NO_AT_BRIDGE=1

    network_mode: "host"

      
    volumes:
      - ros2_ws:/ros2_ws
      - uv_cache:/root/.cache/uv
      - pip_cache:/root/.cache/pip
      - pre-commit_cache:/root/.cache/pre-commit
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ${WORKSPACE_DIR}:${WORKSPACE_DIR}


    tty: true
    stdin_open: true
    command: /usr/bin/bash

volumes:
  ros2_ws:
    name: ros2_ws
  uv_cache:
  pip_cache:
  pre-commit_cache:
